ebi-uniprot/QuickGOBE

annotation-common/src/main/java/uk/ac/ebi/quickgo/annotation/common/document/AnnotationFields.java
annotation-common/src/test/java/uk/ac/ebi/quickgo/annotation/common/document/AnnotationDocMocker.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationController.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/Annotation.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequest.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/converter/AnnotationDocConverter.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/converter/AnnotationDocConverterImpl.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/search/SearchServiceConfig.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/search/SolrQueryResultConverter.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestTest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestValidationIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/service/converter/AnnotationDocConverterImplTest.java
geneproduct-rest/src/test/java/uk/ac/ebi/quickgo/geneproduct/controller/GeneProductControllerIT.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/OBOControllerIT.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/ParameterBindingException.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/ParameterException.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/ResponseExceptionHandler.java
rest-common/src/test/java/uk/ac/ebi/quickgo/rest/search/SearchControllerSetup.java

This branch has the code necessary to filter annotations via the taxon id of the geneproduct associated to the annotation.

Goa 1995 filter by tax

---

quickgo-client/src/main/java/uk/ac/ebi/quickgo/client/model/ontology/OntologyTerm.java
quickgo-client/src/main/java/uk/ac/ebi/quickgo/client/service/converter/ontology/AbstractDocConverter.java
quickgo-client/src/main/resources/search.properties
quickgo-client/src/test/java/uk/ac/ebi/quickgo/client/service/converter/ontology/AbstractDocConverterTest.java
quickgo-client/src/test/java/uk/ac/ebi/quickgo/client/service/search/ontology/OntologySearchIT.java
quickgo-client/src/test/resources/search.properties
rest-common/src/test/java/uk/ac/ebi/quickgo/rest/search/SearchControllerSetup.java

See issue: https://www.ebi.ac.uk/panda/jira/browse/GOA-2191

Add isObsolete to the ontology model.

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/search/SearchServiceConfig.java
annotation-rest/src/main/resources/search.properties
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestConfig.java
annotation-rest/src/test/resources/search.properties
common/src/main/java/uk/ac/ebi/quickgo/common/loader/DbXRefLoader.java
common/src/main/java/uk/ac/ebi/quickgo/common/validator/DbXRefEntity.java
common/src/test/java/uk/ac/ebi/quickgo/common/validator/DbXRefEntityTest.java
deployments/src/main/distros/rest/bin/annotation/application.properties
geneproduct-rest/src/main/java/uk/ac/ebi/quickgo/geneproduct/loader/DbXRefLoader.java
geneproduct-rest/src/main/java/uk/ac/ebi/quickgo/geneproduct/model/GeneProductDbXRefIDFormat.java
geneproduct-rest/src/main/java/uk/ac/ebi/quickgo/geneproduct/service/ServiceConfig.java
geneproduct-rest/src/main/resources/application.properties
geneproduct-rest/src/test/java/uk/ac/ebi/quickgo/geneproduct/loader/DbXRefLoaderTest.java
geneproduct-rest/src/test/java/uk/ac/ebi/quickgo/geneproduct/model/GeneProductXrefEntityTest.java
geneproduct-rest/src/test/resources/application.properties

Add case sensitivity flag for Gene Product ID validation

---

ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/OntologyServiceImpl.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/OBOControllerIT.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/service/OntologyServiceImplTest.java

Remove descendants and ancestors from complete and core fields.
See issue: https://www.ebi.ac.uk/panda/jira/browse/GOA-2282

Remove descendants and ancestors from complete and core fields.

---

indexing/src/main/java/uk/ac/ebi/quickgo/index/ontology/converter/GenericTermToODocConverter.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/ontology/converter/GenericTermToODocConverterTest.java

Fix incorrect ids in the replacements section.
See issue: https://www.ebi.ac.uk/panda/jira/browse/GOA-2290

Fix incorrect ids in the replacements section.

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerRESTIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestTest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestValidationIT.java
annotation-rest/src/test/resources/application.yml

Remove usageIds attribute, and use goId instead.
See issue: https://www.ebi.ac.uk/panda/jira/browse/GOA-2358

Remove usageIds attribute, and use goId instead.

---

ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/controller/OBOController.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/OBOControllerIT.java
sources/src/main/java/uk/ac/ebi/quickgo/graphics/model/GraphImageLayout.java
sources/src/main/java/uk/ac/ebi/quickgo/graphics/ontology/GraphImageResult.java
sources/src/main/java/uk/ac/ebi/quickgo/graphics/service/GraphImageServiceImpl.java
sources/src/test/java/uk/ac/ebi/quickgo/graphics/ontology/GraphImageResultTest.java

introduce new chart sub-resource to contain all coordinate layouting information of the terms within the image chart seen at the "chart" sub-resource.

introduce new chart sub-resource to contain all coordinate layouting information

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationController.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestValidationIT.java
deployments/src/main/distros/index/bin/annotation/application.properties
geneproduct-common/src/main/java/uk/ac/ebi/quickgo/geneproduct/common/document/GeneProductType.java
geneproduct-rest/src/main/java/uk/ac/ebi/quickgo/geneproduct/model/GeneProductRequest.java
geneproduct-rest/src/test/java/uk/ac/ebi/quickgo/geneproduct/search/GeneProductSearchIT.java
indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermsConfig.java
indexing/src/test/resources/application.properties
indexing/src/test/resources/gene_product.gpi
quickgo-client/src/main/java/uk/ac/ebi/quickgo/client/model/presets/impl/CompositePresetImpl.java

Data with this change is now live - so we need to fix it before indexing gene product.

Change rna to miRNA

---

ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/traversal/OntologyGraph.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/traversal/OntologyGraphTest.java

Introducing stop node concept to prevent ancestors of certain (stop) nodes being returned when finding ancestors of a term. These stop nodes are essentially the "roots" of the ontology graph, and makes sure that the real root node which others don't know about (GO:0003673 'obsolete Gene_Ontology') is never returned.

GOA-2336 ontology graph stop nodes

---

indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTerm.java
indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermsAggregationWriter.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermTest.java

Value calculated for ratio was being truncated to 2 decimal places (by design) but of course some ratios where less than this.

Goa 2459 similarity ratio is being calculated as zero

---

annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerIT.java
common/src/main/java/uk/ac/ebi/quickgo/common/validator/DbXRefEntity.java
common/src/test/java/uk/ac/ebi/quickgo/common/validator/DbXRefEntityTest.java

Change gene product id validation to cope with ids structured in the format id:v…ariation or feature.

Change gene product id validation

---

quickgo-client/src/main/java/uk/ac/ebi/quickgo/client/model/presets/impl/CompositePresetImpl.java
quickgo-client/src/test/java/uk/ac/ebi/quickgo/client/controller/PresetsRetrievalIT.java
quickgo-client/src/test/java/uk/ac/ebi/quickgo/client/service/loader/presets/MockPresetDataConfig.java

change preset's goSlim aspect format to show scientific name

---

annotation-common/src/test/java/uk/ac/ebi/quickgo/annotation/common/document/AnnotationDocMocker.java
indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTerm.java
indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermsAggregationWriter.java
indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermsConfig.java
indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermsForSelectedTerm.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermTest.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermsConfigTest.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermsProcessingAndCalculationIT.java
indexing/src/test/resources/application.properties

New integration test to show fix made to calculations.

Goa 2510 fix coterm data

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/converter/AnnotationDownloadFileHeader.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/converter/AnnotationTo.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/converter/AnnotationToGAF.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/converter/AnnotationToGPAD.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/Annotation.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/http/GAFHttpMessageConverter.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/http/GPADHttpMessageConverter.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerDownloadIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/converter/AnnotationDownloadFileHeaderTest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/converter/AnnotationToGAFTest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/converter/AnnotationToGPADTest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationMocker.java

Second version of branch for conversion to download formats.  Includes changes for slimmed results.

Goa 2575 2 convert annotations to download format

---

deployments/src/main/distros/cron/service-checker
deployments/src/main/distros/cron/services.txt
deployments/src/main/distros/rest/bin/status-check

Note (these are currently live for test, running as a cronjob), in preparation for beta.
See our user's goa/.cron/log.txt directory to see the check log.

Goa 2671 automatic restart scripts for rest services

---

indexing/src/main/java/uk/ac/ebi/quickgo/index/QuickGOIndexMain.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/QuickGOIndexMainTest.java

The indexing application (spring boot using batch) now returns a status code indicating success/faliure.

Goa 2874 spring boot indexing exit code

---

sources/src/main/java/uk/ac/ebi/quickgo/graphics/service/GraphImageServiceImpl.java

https://www.ebi.ac.uk/panda/jira/browse/GOA-2966

Change caption of ancestor chart

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationController.java

... and rearrange class according to formatting rules

reveal download swagger annotations

---

sources/src/main/java/uk/ac/ebi/quickgo/graphics/ontology/GraphImage.java
sources/src/main/java/uk/ac/ebi/quickgo/graphics/ontology/GraphPresentation.java

i can show you this live on the VMs with the upgrades (which cause dodgy characters) when you look at this.

Goa 3134 unreadable fonts on web vms

---

common/src/test/java/uk/ac/ebi/quickgo/common/validator/DbXRefEntityValidationTest.java
geneproduct-rest/src/main/java/uk/ac/ebi/quickgo/geneproduct/service/ServiceConfig.java
indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/AnnotationValidator.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/AnnotationMocker.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/AnnotationValidatorTest.java

These changes are in addition to the changes made to the following files which were made in master.
ValidationEntityCheckerIT
DbXRefEntityValidationTest 
DbXRefEntityValidation
AnnotationControllerIT
DbXRefLoaderTestIT

Goa 2922 complex identifiers have changed

---

annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerIT.java
annotation-rest/src/test/resources/application.yml

using fake response from ontology service, now Annotation IT will not depend on ontology

Mock the request to ontology service

---

rest-common/src/main/java/uk/ac/ebi/quickgo/rest/comm/RESTRequesterImpl.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/search/request/converter/RESTFilterConverter.java
rest-common/src/test/java/uk/ac/ebi/quickgo/rest/comm/RESTRequesterImplTest.java
rest-common/src/test/java/uk/ac/ebi/quickgo/rest/search/request/converter/RESTFilterConverterTest.java

see https://www.ebi.ac.uk/panda/jira/browse/GOA-3493

adds backup to rest call if primary fails

---

deployments/src/main/distros/rest/bin/quickgo-client/application.properties
quickgo-client/src/main/java/uk/ac/ebi/quickgo/client/service/loader/presets/reference/ReferencePresetsConfig.java
quickgo-client/src/main/resources/application.properties
quickgo-client/src/test/resources/application.properties

file which is coming should provide them as it is
https://www.ebi.ac.uk/panda/jira/browse/GOA-3508

reference should not validated

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationController.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/download/http/MediaTypeFactory.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerDownloadIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/download/http/MediaTypeFactoryTest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestTest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestValidationIT.java
indexing/pom.xml
parent/pom.xml

see for details
https://www.ebi.ac.uk/panda/jira/browse/GOA-3513

provides download file type as a part of request param
