ebi-uniprot/QuickGOBE

annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestValidationIT.java
common/src/main/java/uk/ac/ebi/quickgo/common/validator/DbXRefEntity.java

All searching / filtering should be case-insensitive; to not do this would be user-hostile. Use the CASE_INSENSITIVE flag when constructing the Pattern object.

Goa 2245 make gene product filter case insensitive

---

annotation-common/src/main/java/uk/ac/ebi/quickgo/annotation/common/document/AnnotationFields.java
annotation-common/src/test/java/uk/ac/ebi/quickgo/annotation/common/document/AnnotationDocMocker.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestValidationIT.java
common/src/main/java/uk/ac/ebi/quickgo/common/converter/HelpfulConverter.java
common/src/test/java/uk/ac/ebi/quickgo/common/converter/HelpfulConverterTest.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/GOControllerIT.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/OBOControllerIT.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/validation/OBOControllerValidationHelperImplTest.java

As a QuickGO user
I would like to be able to filter annotations using a specific group to which a set of gene products belong to
So that I can see annotations that are associated to that/those particular gene product(s)
Acceptance criteria:
If the gene product subset does not match any of the ids on the annotation list, then the result should be empty
If the subset matches at least one of the subsets of a gene product in the list of annotations, then the result should only show the affected annotations
The user can input more than one subset, when this is the case then the ids should be ORed.
This filter criteria can be used in conjunction with other non-related filter criteria
The filter should be case-insensitive

Goa 1998 filter annotations by gene subset

---

annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerIT.java
common/src/main/java/uk/ac/ebi/quickgo/common/loader/DbXRefLoader.java

I've added a test for case sensitivity for RNA, Intact and UniProt gene product ids. When loading the validation regexes in from file they work fine, which is why the jira request for the branch is closed, but this test proves this.

Goa 2241 regex for rna not working

---

indexing/src/main/java/uk/ac/ebi/quickgo/index/ontology/converter/GenericTermToODocConverter.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/ontology/converter/GenericTermToODocConverterTest.java
ontology-common/src/main/java/uk/ac/ebi/quickgo/ontology/common/document/OntologyDocument.java
ontology-common/src/main/java/uk/ac/ebi/quickgo/ontology/common/document/OntologyFields.java
ontology-common/src/test/java/uk/ac/ebi/quickgo/ontology/common/document/OntologyDocMocker.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/model/GOTerm.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/model/OBOTerm.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/converter/AbstractODocConverter.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/converter/CreditsFieldConverter.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/converter/GODiscussionConverter.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/converter/GODocConverter.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/converter/GoDiscussionConverter.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/OBOControllerIT.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/service/converter/AbstractODocConverterTest.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/service/converter/CreditsFieldConverterTest.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/service/converter/GODiscussionConverterTest.java
solr-cores/src/main/cores/ontology/conf/schema.xml

Contains code to add credits (acknowledgments to projects that help fund the creation of the ontology term).

GOA-2237_Add_credits_to_ontology_model

---

indexing/src/main/java/uk/ac/ebi/quickgo/index/ontology/converter/GOTermToODocConverter.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/ontology/converter/GOTermToODocConverterTest.java
ontology-common/src/main/java/uk/ac/ebi/quickgo/ontology/common/document/OntologyDocument.java
ontology-common/src/test/java/uk/ac/ebi/quickgo/ontology/common/document/OntologyDocMocker.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/model/OBOTerm.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/OntologyServiceImpl.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/converter/AbstractODocConverter.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/converter/ReplaceConverter.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/traversal/OntologyGraph.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/traversal/OntologyGraphTraversal.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/OBOControllerIT.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/service/converter/AbstractODocConverterTest.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/traversal/OntologyGraphTest.java
solr-cores/src/main/cores/ontology/conf/schema.xml

Refactor the way the children are loaded into the ontology term. We now use the ontology graph for this.
Add information  on the relationship the child term ids have with the parent.

GOA-2139_Add_parent_relation_to_child_term

---

ontology-common/src/main/java/uk/ac/ebi/quickgo/ontology/common/OntologyRepository.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/ECOControllerIT.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/GOControllerIT.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/OBOControllerIT.java
solr-cores/src/main/cores/ontology/conf/schema.xml

Allows a client to lookup a GO or ECO term by using its secondary identifier.

GOA-2135_Redirect_secondary_terms

---

annotation-common/src/main/java/uk/ac/ebi/quickgo/annotation/common/document/AnnotationDocument.java
annotation-common/src/main/java/uk/ac/ebi/quickgo/annotation/common/document/AnnotationFields.java
annotation-common/src/test/java/uk/ac/ebi/quickgo/annotation/common/document/AnnotationDocMocker.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerIT.java
indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/AnnotationDocumentConverter.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/AnnotationMocker.java

A set of gene products can be defined for a project. This set is the gene products the project is interested in annotating.
QuickGO must allow annotations to be filtered by the gene products sets defined (aka target sets)

Goa 2273 filter annotations by target set

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/Annotation.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/ResponseVerifier.java
solr-cores/src/main/cores/annotation/conf/schema.xml

* schema.xml needed taxonId to be stored
* relevant tests updated to check contents of response
* added test to ensure if taxonId is 0, then nothing is returned, because 0 means invalid taxonId internally (e.g., if source datafile didn't contain it)

GOA-2306_taxon_id_is_0

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestValidationIT.java

The functionality of this is covered by the already existing filtering by GO id capabilities for annotation. Therefore, this branch just removes the 'exact' option for filtering by usage.

GOA-2002: Filter annotation by EXACT ontology usage

---

annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerIT.java
annotation-rest/src/test/resources/search.properties
deployments/src/main/distros/rest/bin/annotation/application.properties

solution for front end is to use the `targetSet` request parameter rather than `geneProductSubset`. Please note, this is subject to change with ongoing back-end refactoring. However, for now, this is the solution.
`targetSet` field in annotation makes use of a non-straight-forward text analyzer. therefore it is not suitable for use as an terms query, hence removing `targetSet` from terms query compatible fields in `application.properties` files.
This PR includes an additional test to ensure that target sets specified by the front end, which contain spaces, e.g., "Reference Genome" can be searched. Previously, this did not work, because a terms query was being issued.

GOA-2422 filtering by gene product set (goal)

---

indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermsConfig.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/AnnotationIndexingBatchIT.java

A copy and paste error meant the CoTermsAll data was being written to the CoTermsManual file.

Goa 2545 fix co terms not being written

---

ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/controller/CoTermController.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/CoTermControllerIT.java

Number of hits is now the total number of Co-occurring terms for a record, not the number the client asked for or is limited too.

Goa 2511 number of hits for coterms

---

quickgo-client/src/main/java/uk/ac/ebi/quickgo/client/model/ontology/OntologyRequest.java

This field was not being shown in the swagger-ui. Fix simply involved providing a getter and setter, which swagger relies upon.

fix swagger documentation for QuickGO client's facets

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestValidationIT.java

500->600 for number of GO term ids allowed by the front end.

Goa 2594 increase go term limit

---

annotation-rest/src/test/resources/application.yml
deployments/src/main/distros/rest/bin/annotation/application.yml
indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/AnnotationConfig.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/AnnotationDocumentWriteRetryHelper.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/AnnotationIndexingRetriesSolrWritesWithFailureIT.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/AnnotationIndexingRetriesSolrWritesWithSuccessIT.java
indexing/src/test/resources/application.properties

This uses Spring Batch's retry + backoff policy api.
Given a state where Sorlcloud is busy during indexing (e.g,. perhaps performing some Zookeeper maintenance), the idea is the following:
* sending a "chunk" of documents to be indexed finds that Solrcloud is busy, and the indexing application hits a `RemoteSolrException`
* wait for a configurable period of time, before resending the same chunk of documents (e.g., to give Solrcloud some maintenance time)
* if the subsequent retry fails, continue retrying a configurable number of times.
* if all retries fail, then indexing can fail (e.g., indicating there is something wrong with Solrcloud)
* if retrying a request succeeds, great.

adding retry logic whilst indexing, e.g., when Solrcloud is busy

---

annotation-common/src/test/java/uk/ac/ebi/quickgo/annotation/common/AnnotationRepositoryIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AbstractFilterAnnotationByOntologyRESTIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerDownloadIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerStatisticsIT.java
common/src/test/java/uk/ac/ebi/quickgo/common/store/BasicTemporaryFolder.java
common/src/test/java/uk/ac/ebi/quickgo/common/store/TemporarySolrDataStore.java
deployments/src/main/distros/solr/index/bin/annotation/application.properties
geneproduct-common/src/test/java/uk/ac/ebi/quickgo/geneproduct/common/GeneProductRepositoryIT.java
geneproduct-rest/src/test/java/uk/ac/ebi/quickgo/geneproduct/controller/GeneProductControllerIT.java
geneproduct-rest/src/test/java/uk/ac/ebi/quickgo/geneproduct/search/GeneProductUserQueryScoringIT.java
indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermsConfig.java
indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermsConfigProperties.java
indexing/src/main/resources/application.properties
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/AnnotationIndexingBatchIT.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/AnnotationIndexingRetriesSolrWritesWithFailureIT.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/AnnotationIndexingRetriesSolrWritesWithSuccessIT.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/CoTermIndexingBatchIT.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/annotation/coterms/CoTermConfigTest.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/geneproduct/GeneProductIndexingBatchIT.java
indexing/src/test/java/uk/ac/ebi/quickgo/index/ontology/OntologyIndexingBatchIT.java
indexing/src/test/resources/application.properties
ontology-common/src/test/java/uk/ac/ebi/quickgo/ontology/common/OntologyRepositoryIT.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/OBOControllerIT.java
quickgo-client/src/test/java/uk/ac/ebi/quickgo/client/service/search/ontology/OntologyUserQueryScoringIT.java
rest-common/src/test/java/uk/ac/ebi/quickgo/rest/search/SearchControllerSetup.java

It was noticed that the tests for annotation indexing (which includes testing co-terms), and co-term writing, wasn't maintaining control over where the file was being written to. Also, multiple test classes with different concerns were writing to the same files.
This PR puts the co-term specific properties into a separate class, which is populated through @ConfigurationProperties, and an instance of which is provided as a @Bean. The tests then are able to override this bean directly, and can write to a temporary location (BasicTemporaryFolder).
NB. This move to @ConfigurationProperties seemed relevant since we have an ongoing effort to use this style of property configuration over @Value, as recommended by the Spring community.
NB2. The use of @ConfigurationProperties means we'll need to …

Goa 2457 configurable co term test

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AbstractFilterAnnotationByOntologyRESTIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerStatisticsIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestTest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/AnnotationRequestValidationIT.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/search/request/FilterRequest.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/search/request/converter/FilterConverterFactory.java

Jira user story info:
**AS** the annotation GO term and ECO term filter 
**I WOULD LIKE TO** always specify the goUsage / evidenceCodeUsage value 
**SO THAT I CAN** know explicitly what filter value I am asking for.
**AS** a client of the QuickGO API 
**I WOULD LIKE TO** get descendants as default for goUsage / evidenceCodeUsage 
**SO THAT I CAN**  omit that filter value if I want.
_Scenarios:_
goId=XX&goUsage=exact => exact on XX
goId=XX&goUsage=descendants => descendants of XX
goId=XX => descendants of XX
goId=XX&goUsage=slim => slim of XX

Goa 2736 go and eco filter defaults

---

quickgo-client/src/main/java/uk/ac/ebi/quickgo/client/model/ontology/OntologyRequest.java
quickgo-client/src/test/java/uk/ac/ebi/quickgo/client/model/ontology/OntologyRequestValidationIT.java
quickgo-client/src/test/java/uk/ac/ebi/quickgo/client/service/search/ontology/OntologySearchIT.java
rest-common/src/test/java/uk/ac/ebi/quickgo/rest/search/SearchControllerSetup.java

As a QuickGO user,
When I search for ontology aspects, I would like to be able to search for Process/Function/Component (case insensitive).
Then I want to retrieve all terms matching the requested aspect.
Note. (Previously, one could search for, e.g., biological_process, but this behaviour was changed to the more user friendly versions Process/Function/Component).

aligns quickgo-client's aspect filter with that of the contents of the ontology core

---

indexing/src/main/java/uk/ac/ebi/quickgo/index/annotation/AnnotationConfig.java
indexing/src/main/java/uk/ac/ebi/quickgo/index/geneproduct/GeneProductConfig.java
solr-cores/src/main/cores/geneproduct/conf/solrconfig.xml

align geneproduct indexing writing with that of annotations, which has better document write rate: no searcher needs to be available during indexing; defer committing to solr itself + a final commit at end of indexing (as opposed to on every chunk write); use solrwriter class, which prints rate info

Align geneproduct indexing with that of annotations

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/download/http/MediaTypeFactory.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/download/http/MediaTypeFactoryTest.java

When a download file is requested from the QuickGO backend, if the character set is not defined as part of the accept header, then the media type definition created does not match what is expected - the result is the file type i.e what should be .tsv or .gaf etc appears as null.
We can make the test of media type to be more simple and flexible to avoid these nulls.

Goa 3070 improve download file name

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/StatisticsByType.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/statistics/AnnotationStatisticsService.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerStatisticsIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/StatsResponseVerifier.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/StatisticsByTypeTest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/StatisticsGroupTest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/service/converter/WorkbookFromStatisticsImplTest.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/search/results/AggregateResponse.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/search/results/AggregateResponseBuilder.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/search/solr/AggregateToStringConverter.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/search/solr/SolrAggregationHelper.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/search/solr/SolrResponseAggregationConverter.java
rest-common/src/test/java/uk/ac/ebi/quickgo/rest/search/results/AggregateResponseBuilderTest.java
rest-common/src/test/java/uk/ac/ebi/quickgo/rest/search/results/AggregateResponseTest.java
rest-common/src/test/java/uk/ac/ebi/quickgo/rest/search/solr/AggregateRequestToStringConverterTest.java
rest-common/src/test/java/uk/ac/ebi/quickgo/rest/search/solr/SolrAggregationHelperTest.java
rest-common/src/test/java/uk/ac/ebi/quickgo/rest/search/solr/SolrResponseAggregationConverterTest.java

Achieve this by adding numBuckets:true to get agg_facet request
Changes response from solr to 
"unique_geneProductId": 41458221,
"agg_evidenceCode": {
"numBuckets": 35,
"buckets": [
{
"val": "ECO:0000256",
"count": 88001168,
"unique_geneProductId": 38321802,
"count_id": 88001168
},
{
"val": "ECO:0000323",
"count": 50206450,
"unique_geneProductId": 25361638,
"count_id": 50206450
},
...
And the resulting json from the rest service
"groupName": "annotation",
"totalHits": 27,
"types": [
{
"type": "reference",
"distinctValueCount": 9,
"values": [
{
"key": "PMID:25911094",
"percentage": 0.4074074074074074,
"hits": 11,
"name": null
},
{
"key": "GO_REF:0000037",
"percentage": 0.14814814814814814,
"hits": 4,
"name": null
},
{
"key": "GO_REF:0000107",
"percentage": 0.14814814814814814,
"hits": 4, …

Goa 2943 distinct facet count in statistics

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/comm/rest/ontology/converter/SlimmingFilterConverter.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/comm/rest/ontology/model/OntologyRelatives.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AbstractFilterAnnotationByOntologyRESTIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/FilterAnnotationByGORESTIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/service/comm/rest/ontology/descendants/SlimmingFilterConverterTest.java
annotation-rest/src/test/resources/application.yml
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/controller/GOController.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/model/SlimTerm.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/OntologyService.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/OntologyServiceImpl.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/traversal/TermSlimmer.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/GOControllerIT.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/traversal/TermSlimmerTest.java

Previously, the ontology slimming service showed a map of <termId, slimmedToTermIdList>, where the keys of this map is the entire ontology. A new use case has come in where it is wanted that the keys of this map to be filtered to only those they specify. Therefore, a new request parameter `slimsFromIds` has been introduced to filter the keys to only those that are desired.

allow filtering of slimmed from terms for ontology slimming service

---

annotation-common/src/test/java/uk/ac/ebi/quickgo/annotation/common/document/AnnotationDocMocker.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationController.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/comm/rest/ontology/model/BasicOntology.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/comm/rest/ontology/transformer/completablevalue/EvidenceNameInjector.java
annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/service/search/SearchServiceConfig.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerStatisticsDownloadIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerStatisticsIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/StatsResponseVerifier.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/StatsSetupHelper.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/service/comm/rest/ontology/transformer/EvidenceNameInjectorTestHelper.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/service/comm/rest/ontology/transformer/completablevalue/EvidenceNameInjectorTest.java
annotation-rest/src/test/resources/application.yml

The statistics json will now contain the term names (go and eco) and taxon names.

Goa 3078 add term and taxon names to statistics endpoint

---

annotation-rest/src/main/java/uk/ac/ebi/quickgo/annotation/model/StatisticsByType.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/controller/AnnotationControllerStatisticsIT.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/model/StatisticsByTypeTest.java
annotation-rest/src/test/java/uk/ac/ebi/quickgo/annotation/service/statistics/SlimmedStatsInjectorTest.java
rest-common/src/main/java/uk/ac/ebi/quickgo/rest/search/results/AggregateResponse.java

Use the statistics bucket size rather than value count if bucket size is greater.
Rename distinctValueCount to approximateCount to reflect the fact its estimated.

Goa 3124 distinct value count does not match result size

---

ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/controller/OBOController.java
ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/model/GraphRequest.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/OBOControllerIT.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/model/GraphRequestValidationIT.java
sources/src/main/java/uk/ac/ebi/quickgo/graphics/ontology/GraphImage.java
sources/src/main/java/uk/ac/ebi/quickgo/graphics/ontology/GraphPresentation.java
sources/src/main/java/uk/ac/ebi/quickgo/graphics/ontology/OntologyGraph.java
sources/src/main/java/uk/ac/ebi/quickgo/graphics/ontology/TermNode.java
sources/src/main/java/uk/ac/ebi/quickgo/graphics/service/GraphImageService.java
sources/src/main/java/uk/ac/ebi/quickgo/graphics/service/GraphImageServiceImpl.java
sources/src/test/java/uk/ac/ebi/quickgo/graphics/ontology/GraphPresentationTest.java

~~I've tried to make the creation of the GraphPresentation as clean as possible...
I've used Option in the request handling class GraphRequest - I think its a good fit and makes the interrogation of that class super easy.~~
This wouldn't play with swagger - will Optional<Integer> was OK with a return type from GraphRequest getters, Optional<Boolean> would not work.

Goa 3112 specify ancestor chart options

---

ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/service/OntologyServiceImpl.java
ontology-rest/src/test/java/uk/ac/ebi/quickgo/ontology/controller/GOControllerIT.java

This means terms will always map to themselves, as required by https://www.ebi.ac.uk/panda/jira/browse/GOA-3158

Remove filter during slimming that omits identity mappings.

---

ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/controller/AnnotationExtensionController.java

Spring framework will consider response extension after dot. This will allow to pass every thing as variable value.

candidate can have a dot . in it
